### ISSUE TITLE
Thoth 2017 port

### ISSUE THREAD

**Issue by pagojo** [rgrove/thoth#10]
@rgrove thanks for Thoth !

I resurrected Thoth [here](https://github.com/pagojo/rethoth) 

Maybe you can put a link to this URL for people to find easily. My intention is to maintain it  :-)

**Comment by rgrove** [comment]
Thanks! I've added a link.

**Comment by pagojo** [comment]
Great! 
I guess I will now have to create a new account on RubyGems.org and rename the gem to avoid name clashes.
